### ISSUE TITLE
[Question] What is the meaning of train_pcd.

### ISSUE THREAD

**Issue by feyhong1112** [HeegerGao/equiformer_v2_pcd#1]
Sorry to ask you. I want to ask about the terminology of this
Specifically : input_channel, "RGB + 1 type-1 feature", input type and graph_pcd_num
How you determine to assign batch like that?

Thank you for visit my post.

**Comment by feyhong1112** [comment]
I seem get a little bit do you implement [3, 1] is the 3 = RGB and 1 is the type 1 feature vector I am I right?
But how it link to feature that you input?

**Comment by HeegerGao** [comment]
Hi @feyhong1112 , I am sorry that this repo is just an incomplete implementation. We are still working on it. We will let you know when this is finished.

**Comment by feyhong1112** [comment]
Thank youuu!! So much
